import { Card } from "@/components/ui/card";
import { CalendarDays } from "lucide-react";

export default function RoadmapCard({ analysis }) {
  if (!analysis) return null;

  return (
    <Card className="rounded-3xl border border-slate-800 bg-slate-900 p-8">

      <div className="mb-8 flex items-center gap-3">

        <div className="rounded-xl bg-emerald-500/10 p-3">
          <CalendarDays
            size={22}
            className="text-emerald-400"
          />
        </div>

        <div>

          <h2 className="text-2xl font-bold text-white">
            30-Day Learning Roadmap
          </h2>

          <p className="text-sm text-slate-400">
            Personalized learning plan generated by RepoLens AI.
          </p>

        </div>

      </div>

      <div className="space-y-5">

        {analysis.roadmap.map((week) => (
          <div
            key={week.week}
            className="flex gap-5 rounded-2xl border border-slate-800 bg-slate-950 p-5"
          >

            <div className="flex h-12 w-12 items-center justify-center rounded-xl bg-blue-500/10 text-lg font-bold text-blue-400">
              {week.week}
            </div>

            <div>

              <h3 className="font-semibold text-white">
                Week {week.week}
              </h3>

              <p className="mt-2 leading-7 text-slate-400">
                {week.goal}
              </p>

            </div>

          </div>
        ))}

      </div>

    </Card>
  );
}